services:
  app:
    build: .
    volumes:
      - ./dumps:/app/dumps
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - CREATE_DIRS_AUTOMATICALLY=true
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/autoria
      - MAX_PAGES=10
      - MAX_TICKETS_PER_RUN=100
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 